export const LOAD_BOOKS = 'LOAD_BOOKS';
export const LOAD_BOOKS_ERROR = 'LOAD_BOOKS_ERROR';
export const LOAD_BOOKS_LOADING = 'LOAD_BOOKS_LOADING';
export const LOAD_BOOK_BY_ID = 'LOAD_BOOK_BY_ID';
export const LOAD_BOOK_BY_ID_LOADING = 'LOAD_BOOK_BY_ID_LOADING';
export const CLEAR_BOOK_SINGLE = 'CLEAR_BOOK_SINGLE';
